apiVersion: v1
kind: Service
metadata:
  name: service-461server
spec:
  selector:
    app: 461server
  ports:
  - name: udp
    protocol: UDP
    port: 1453
    targetPort: 12235
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 461server
spec:
  selector:
    matchLabels:
      app: 461server
  replicas: 3
  template:
    metadata:
      labels:
        app: 461server
    spec:
      containers:
      - name: 461server
        image: 461server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 12235
