apiVersion: v1
kind: Service
metadata:
  name: service-server
spec:
  selector:
    app: server
  ports:
  - name: udp
    protocol: UDP
    port: 1453
    targetPort: 12235
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 12235
