apiVersion: v1
kind: Service
metadata:
  name: simple-service-lb
spec:
  selector:
    app: simple-service-server
  ports:
  - port: 1453
    targetPort: 12235
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-service-server
spec:
  selector:
    matchLabels:
      app: simple-service-server
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-service-server
    spec:
      containers:
      - name: simple-service-server
        image: public.ecr.aws/g6f8c0h5/kubernerds:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 12235
