apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: us-east-1
managedNodeGroups:
  - name: job-manager
    instanceType: t3a.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    tags:
      'Project': 'KubernetesNoob'